resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/davidk355/n-test.git
      branch: master

  - name: resource-deploy-web-app
    type: cf
    source:
      api: {{cf-local-api}}
      username: {{cf-local-username}}
      password: {{cf-local-password}}
      organization: {{cf-local-organization}}
      space: {{cf-local-space}}
      skip_cert_check: true

jobs:
  - name: job-deploy-app
    serial: true
    plan:
    - {get: source-code, trigger: true}
    - task: build
      privileged: true
      file: source-code/ci/tasks/build.yml
      path: source-code
    - put: resource-deploy-web-app
      params:

        manifest: source-code-built/manifest.yml
